# -------------------------
# Data
# -------------------------
data:
  root: data/LibriSpeech/
  pattern: "*.pt"
  split: "train-clean-100"
  return_wav: False
  kill_singletons: 0
  spk_id_map: 


dataloader:
  batch_size: 32
  num_workers: 0
  pad_value: -1

# -------------------------
# Model
# -------------------------
model:
  embeddings_path: /data/LJSpeech-1.1/embeddings.pt
  filter_channels: 256
  kernel_size: 3
  p_dropout: 0.1
  lr: 0.001
  weight_decay: 0.0
  loss_type: l1 # l1 | mse | huber
  padding_idx: -1
  do_log: true
  use_spk_id: true
  spk_id_path: 
  spk_embedding_dim: 128

# -------------------------
# Trainer
# -------------------------
trainer:
  max_epochs: 50
  accelerator: mps # cpu | gpu | auto
  devices: auto
  precision: 32 # or 16-mixed
  log_every_n_steps: 50
  version: log_50e
